builds:
  - goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
  - goos:
      - darwin
    goarch:
      - amd64
release:
  github:
    owner: the-lightning-land
    name: balanced
  draft: true
archive:
  wrap_in_directory: true
sign:
  artifacts: checksum