// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	IdentityPubKey       string   `protobuf:"bytes,3,opt,name=identityPubKey,proto3" json:"identityPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetInfoResponse) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *GetInfoResponse) GetIdentityPubKey() string {
	if m != nil {
		return m.IdentityPubKey
	}
	return ""
}

type BalanceRequest struct {
	FromChanId           uint64   `protobuf:"varint,1,opt,name=fromChanId,proto3" json:"fromChanId,omitempty"`
	ToChanId             uint64   `protobuf:"varint,2,opt,name=toChanId,proto3" json:"toChanId,omitempty"`
	AmtMsat              uint64   `protobuf:"varint,3,opt,name=amtMsat,proto3" json:"amtMsat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetFromChanId() uint64 {
	if m != nil {
		return m.FromChanId
	}
	return 0
}

func (m *BalanceRequest) GetToChanId() uint64 {
	if m != nil {
		return m.ToChanId
	}
	return 0
}

func (m *BalanceRequest) GetAmtMsat() uint64 {
	if m != nil {
		return m.AmtMsat
	}
	return 0
}

type BalanceResponse struct {
	Rebalanced           bool     `protobuf:"varint,1,opt,name=rebalanced,proto3" json:"rebalanced,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetRebalanced() bool {
	if m != nil {
		return m.Rebalanced
	}
	return false
}

func init() {
	proto.RegisterType((*GetInfoRequest)(nil), "rpc.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "rpc.GetInfoResponse")
	proto.RegisterType((*BalanceRequest)(nil), "rpc.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "rpc.BalanceResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xfb, 0x8f, 0xa6, 0x9d, 0x43, 0x2a, 0xab, 0x48, 0xe8, 0xa1, 0xc8, 0x1e, 0xc4, 0x53,
	0x41, 0x05, 0x3f, 0x80, 0x1e, 0xa4, 0x88, 0x20, 0xfb, 0x0d, 0x36, 0xe9, 0x04, 0x83, 0x66, 0x27,
	0xee, 0x4e, 0x85, 0x7c, 0xfb, 0x92, 0xcd, 0x26, 0x34, 0x39, 0xbe, 0xf7, 0x78, 0xfb, 0x9b, 0x99,
	0x85, 0xb5, 0xad, 0xb2, 0x7d, 0x65, 0x89, 0x49, 0xcc, 0x6d, 0x95, 0xc9, 0x2b, 0x88, 0xdf, 0x91,
	0x0f, 0x26, 0x27, 0x85, 0x7f, 0x27, 0x74, 0x2c, 0x7f, 0x60, 0xd3, 0x3b, 0xae, 0x22, 0xe3, 0x50,
	0x24, 0x10, 0xfd, 0xa3, 0x75, 0x05, 0x99, 0x64, 0x7a, 0x37, 0x7d, 0x58, 0xab, 0x4e, 0x8a, 0x5b,
	0x58, 0x66, 0x54, 0x96, 0x05, 0x27, 0x33, 0x1f, 0x04, 0x25, 0xee, 0x21, 0x2e, 0x8e, 0x68, 0xb8,
	0xe0, 0xfa, 0xeb, 0x94, 0x7e, 0x60, 0x9d, 0xcc, 0x7d, 0x3e, 0x72, 0x65, 0x0e, 0xf1, 0xab, 0xfe,
	0xd5, 0x26, 0xc3, 0x80, 0x17, 0x3b, 0x80, 0xdc, 0x52, 0xf9, 0xf6, 0xad, 0xcd, 0xe1, 0xe8, 0x71,
	0x0b, 0x75, 0xe1, 0x88, 0x2d, 0xac, 0x98, 0x42, 0x3a, 0xf3, 0x69, 0xaf, 0x9b, 0x39, 0x75, 0xc9,
	0x9f, 0x4e, 0xb3, 0xc7, 0x2d, 0x54, 0x27, 0xe5, 0x23, 0x6c, 0x7a, 0x4e, 0x58, 0x6a, 0x07, 0x60,
	0x31, 0x6d, 0xcd, 0x16, 0xb4, 0x52, 0x17, 0xce, 0x53, 0x0d, 0x51, 0xa8, 0x88, 0x17, 0x88, 0xc2,
	0x49, 0xc4, 0xf5, 0xbe, 0x39, 0xe0, 0xf0, 0x64, 0xdb, 0x9b, 0xa1, 0xd9, 0x02, 0xe4, 0xa4, 0xe9,
	0x75, 0x4f, 0xb4, 0xbd, 0xe1, 0xae, 0xa1, 0x37, 0x1a, 0x4c, 0x4e, 0xd2, 0xa5, 0xff, 0xa0, 0xe7,
	0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x00, 0x15, 0x81, 0xad, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BalanceClient is the client API for Balance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalanceClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type balanceClient struct {
	cc *grpc.ClientConn
}

func NewBalanceClient(cc *grpc.ClientConn) BalanceClient {
	return &balanceClient{cc}
}

func (c *balanceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/rpc.Balance/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/rpc.Balance/Balance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServer is the server API for Balance service.
type BalanceServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	Balance(context.Context, *BalanceRequest) (*BalanceResponse, error)
}

func RegisterBalanceServer(s *grpc.Server, srv BalanceServer) {
	s.RegisterService(&_Balance_serviceDesc, srv)
}

func _Balance_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Balance/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Balance/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).Balance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Balance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Balance",
	HandlerType: (*BalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Balance_GetInfo_Handler,
		},
		{
			MethodName: "Balance",
			Handler:    _Balance_Balance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
